#include "veikkconfig.h"
#include "ui_main.h"
#include "qpressurecurvescene.h"
#include "qscreenmapscene.h"

// set up widgets
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow{parent}, ui{new Ui::MainWindow} {
    // basic ui setup (auto-generated by qt designer)
    ui->setupUi(this);

    QGraphicsView *pressureCurveView, *screenMapView;

    pressureCurveView = findChild<QGraphicsView *>("pressure_curve_view");
    pressureCurveView->setScene(new QPressureCurveScene{});
    pressureCurveView->scale(300.0/1.21, -300.0/1.21);

    screenMapView = findChild<QGraphicsView *>("screen_map_view");
    screenMapView->setScene(new QScreenMapScene{});
    screenMapView->scale(500.0/1920, 500.0/1080);
}

MainWindow::~MainWindow() {
    delete ui;
}
